In [1]:
import numpy as np

# GridWorld Size (4x4)
N = 4  
num_states = N * N  

# Rewards (-1 per move, 0 for terminal state)
reward = -1
terminal_state = num_states - 1  # Bottom-right corner

# Discount factor (Gamma) and Convergence Threshold
gamma = 1.0
theta = 1e-4  

# Actions: Up, Down, Left, Right
actions = [(-1, 0), (1, 0), (0, -1), (0, 1)]  

# Initialize Value Function (V) to 0 for all states
V = np.zeros(num_states)

# Function to get next state and handle boundaries
def get_next_state(s, action):
    row, col = divmod(s, N)
    new_row, new_col = row + action[0], col + action[1]

    # Stay within grid boundaries
    if 0 <= new_row < N and 0 <= new_col < N:
        return new_row * N + new_col  # Convert (row, col) to state index
    return s  # If move is out of bounds, stay in the same state

# Value Iteration Algorithm
while True:
    delta = 0  # Track max change in V(s)
    V_new = np.copy(V)  

    for s in range(num_states):
        if s == terminal_state:
            continue  # Skip terminal state

        v = 0  # Value update for current state
        for action in actions:
            s_prime = get_next_state(s, action)
            v += (1 / len(actions)) * (reward + gamma * V[s_prime])  # Bellman Update

        V_new[s] = v  # Update value function
        delta = max(delta, abs(V_new[s] - V[s]))  # Track max change

    V = V_new  # Update value function
    if delta < theta:
        break  # Stop if converged

# Print Final Value Function
print("Final Value Function:")
print(V.reshape(N, N))


Final Value Function:
[[-59.42367735 -57.42387125 -54.2813141  -51.71012579]
 [-57.42387125 -54.56699476 -49.71029394 -45.13926711]
 [-54.2813141  -49.71029394 -40.85391609 -29.99766609]
 [-51.71012579 -45.13926711 -29.99766609   0.        ]]
